apiVersion: v1
data:
  configs-ddtrace.ini:
    {{if .Values.request_init_hook }}ddtrace.request_init_hook={{ .Values.request_init_hook }}{{end}}

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: ddtrace-php-ini
