kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root /project/public;
        server_name _;

        location / {
          try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;

          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
        #   fastcgi_pass 127.0.0.1:9000;
          fastcgi_pass php:9000;
        }
      }
    }
