apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -c
    kompose.image-pull-policy: Always
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
      - image: datadog/docker-library:dd_trace_loadtest_real_world_app
        imagePullPolicy: Always
        name: loadtest
        command: ["loadtest", "-c", "10", "--rps", "40", "http://nginx/api/articles"]
        resources:
          limits:
            memory: "300M"
            cpu: "200m"
          requests:
            memory: "300M"
            cpu: "200m"
      - image: datadog/docker-library:dd_trace_node_symfony_real_world_app
        imagePullPolicy: Always
        name: node
        env:
        - name: DD_AGENT_HOST
          value: ddagent
        resources:
          requests:
            memory: "400M"
            cpu: "10m"
          limits:
            memory: "400M"
            cpu: "10m"
      restartPolicy: Always
status: {}
