apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -c
    kompose.image-pull-policy: Always
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - name: memcache
        image: memcached:alpine
        ports:
        - containerPort: 11211
        resources:
          limits:
            memory: "100M"
            cpu: "100m"
          requests:
            memory: "100M"
            cpu: "100m"
      - name: mysql
        env:
        - name: MYSQL_DATABASE
          value: project
        - name: MYSQL_PASSWORD
          value: project
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: project
        image: datadog/docker-library:dd_trace_mysql_symfony_real_world_app
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "300M"
            cpu: "200m"
          requests:
            memory: "300M"
            cpu: "200m"
      - name: php
        env:
        - name: DDTRACE_DEB_URL
          value: {{ .Values.deb_url }}
        - name: DD_TRACE_GLOBAL_TAGS
          value: kube_namespace:{{ .Release.Namespace }}{{ if .Values.global_tags }},{{ .Values.global_tags }}{{ end }}
        - name: DD_AGENT_HOST
          value: ddagent
        - name: DATABASE_URL
          value: mysql://project:project@127.0.0.1:3306/project
        image: datadog/docker-library:dd_trace_php_symfony_real_world_app_71
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "300M"
            cpu: "1000m"
          requests:
            memory: "300M"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /usr/local/etc/php/conf.d/99-ddtrace.ini
          subPath: 99-ddtrace.ini
          name: ddtrace-php-ini
        - mountPath: /etc/php-fpm.conf
          subPath: php-fpm.conf
          name: ddtrace-php-ini
      restartPolicy: Always
      volumes:
      - name: ddtrace-php-ini
        configMap:
          defaultMode: 0644
          name: ddtrace-php-ini
status: {}
