apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -c
    kompose.image-pull-policy: Always
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - env:
        - name: DDTRACE_DEB_URL
        - name: DD_AGENT_HOST
          value: ddagent
        image: datadog/docker-library:dd_trace_php_symfony_real_world_app_71
        imagePullPolicy: Always
        name: php
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/etc/php/conf.d/99-ddtrace.ini
          subPath: 99-ddtrace.ini
          name: ddtrace-php-ini
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: ddtrace-php-ini
          items:
          - key: configs-ddtrace.ini
            path: 99-ddtrace.ini
        name: ddtrace-php-ini
status: {}
