version: '3.3'

configs:
  ddtrace-php-ini:
    file: configs-ddtrace.ini

services:
    php:
        build:
            context: "./"
            dockerfile: docker/php/Dockerfile
        image: datadog/docker-library:dd_trace_php_symfony_real_world_app_71_xdebug
        labels:
            kompose.image-pull-policy: Always
        environment:
            - "DD_AGENT_HOST=ddagent"
            # - "DDTRACE_DEB_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.17.0/datadog-php-tracer_0.17.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://22544-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.17.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://23824-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.18.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://24002-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.18.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://24979-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.18.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://25047-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.18.0_amd64.deb"
            # - "DDTRACE_DEB_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.29.0/datadog-php-tracer_0.29.0_amd64.deb"
            - "DDTRACE_DEB_URL=https://54411-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_0.30.0_amd64.deb"
            # - "DD_SAMPLING_RATE=0.5"
        links:
            - mysql
            - memcache
        depends_on:
            - mysql
            - ddagent
        ports:
            - "9000:9000"
        expose:
            - 9000
        # volumes:
            # - "./:/project:cached"
        configs:
            - source: ddtrace-php-ini
              target: /usr/local/etc/php/conf.d/99-ddtrace.ini
              mode: 0644
    nginx:
        build:
            context: "./"
            dockerfile: docker/nginx/Dockerfile
        image: datadog/docker-library:dd_trace_nginx_symfony_real_world_app
        labels:
            kompose.image-pull-policy: Always
        depends_on:
            - php
        links:
            - php
        ports:
            - "80:80"
        expose:
            - 80

    mysql:
        build: docker/mysql
        image: datadog/docker-library:dd_trace_mysql_symfony_real_world_app
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=project"
            - "MYSQL_PASSWORD=project"
            - "MYSQL_DATABASE=project"
        ports:
            - "3306:3306"
        expose:
            - 3306

    node:
        build:
            context: "./"
            dockerfile: docker/node/Dockerfile
        labels:
            kompose.image-pull-policy: Always
        image: datadog/docker-library:dd_trace_node_symfony_real_world_app
        depends_on:
            - nginx
        deploy:
            replicas: 2

    memcache:
        image: memcached:alpine
    ddagent:
        image: datadog/agent:6.12.1
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "-X", "HEAD", "http://localhost:8126"]
        #     interval: 10s
        #     timeout: 2s
        #     retries: 2
        links:
            - mysql
        # volumes:
        #     - /var/run/docker.sock:/var/run/docker.sock
        #     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
        #     - /proc/:/host/proc/
        environment:
            - DD_APM_ENABLED=true
            - DD_PROCESS_AGENT_ENABLED=true
            - DD_BIND_HOST=0.0.0.0
            - DD_API_KEY=9779170d9bdfb020700635e1852c6ec7
            - DD_APM_MAX_CPU_PERCENT=1
            - DD_APM_MAX_MEMORY=120000000
        ports:
            - "8126:8126"
        expose:
            - 8126

    loadtest:
        depends_on:
            - nginx
        build:
            context: "./"
            dockerfile: docker/loadtest/Dockerfile
        image: datadog/docker-library:dd_trace_loadtest_real_world_app
