version: '3'
services:
  nginx:
    ports:
      - "8000:80"
  mysql:
    ports:
      - "3306:3306"
  php:
    depends_on: [ 'ddagent', 'mysql' ]
  memcache:
    image: memcached:alpine

  ddagent:
    image: datadog/agent
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "HEAD", "http://localhost:8126"]
      interval: 10s
      timeout: 2s
      retries: 2
    links:
      - mysql
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc/mounts:/host/proc/mounts:ro
        - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY=5fa68aae23e4822d6f778f8d163f85e8
    ports:
      - "8126:8126"
    expose:
      - 8126
