## keep this a secret
dd_api_key: 5fa68aae23e4822d6f778f8d163f85e8
## value of request_init_hook set in 99-ddtrace.ini file
request_init_hook:
## file to fetch and install at the start of container
deb_url:
## Global tags added to DD_TRACE_GLOBAL_TAGS env variable
global_tags:
