apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -c
    kompose.image-pull-policy: Always
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: php
status:
  loadBalancer: {}
